//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tastehub.Core.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public int ImageID { get; set; }
        public string ImageName { get; set; }
        public byte[] ImageData { get; set; }
        public string PathPrimary { get; set; }
        public string PathSecondary { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        public string UploadedBy { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    
        public virtual ImageCategory ImageCategory { get; set; }
    }
}
